project:
  type: website

website:
  title: "绫戴丽的快递钟楼"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shinariay/gh-publish
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


