---
title: "Now You May Escape Reloaded"
author: "绫戴丽赫本"
date: "2022-11-03"
categories: [Story]
---

# Part 1

倘若这世界是一场戏剧，它一定是无悲无喜的。

没有发人深思的悲伤，也没有深沉炽烈的幻想。

它只是一出乏味无趣的叙事剧，做出成百上千次相同的演出。

只等着演员变得年老体衰，戏服变得褪色残破。

随后，将之吞噬殆尽。

而我们，不过是依偎在臃肿的教典上，不断吸吮着脓疮的修士。

贪婪也好、虔诚也罢。

无论多少次，能得到的也只是一滩令人作呕的汁水。

因为这世界就像蜘蛛，编织出无数张同质的网。

那些名为妄想的飞蛾，终会陷入其中。

这纵横交错的小小蛛网里，囚禁我们的不是铁笼，而是孤岛。

洪流冲刷着岛岸，将每个胆敢逾越的人，悉数修正。

海浪声，交织成一串嘈杂的闹铃。

将那些落入船难的思绪冲上滩涂。

啪嗒。一只手按在闹钟上，扼紧它的喉咙。

6:40，这是我睁开眼看到的时间。

再度与每天的第一缕阳光幽会，又或是说，吻别这终将离去的太阳。

起床。重新唤醒这僵直的身体。

每次睡眠都无异于一次短暂的死亡，直到再也无法苏醒为止。

洗漱。牙刷的毛刺深深嵌入牙龈里，刮出血痕。

一个正常的人每天都该刷牙，我想。但我不能说，从不刷牙的人就不正常。

不过至少，牙科医生会觉得那样的人不正常。

穿衣。白色的衬衣、黑色的外套和长裤。全都一尘不染，熨烫得毫无褶皱。

这些勾勒出我一米九的健硕身材。可加上略显憔悴的面孔，却只显得佝偻。

也许，该找个时间好好休息一阵。

我来到起居室内的开放式厨房，打开放在置物隔断第一排的收音机。

悠扬的乐曲从中响起，是儒勒.马斯奈的《沉思曲》。

我打开烤面包机，将吐司片放入其中，趁吐司机运作时去做别的事。

煎锅里的油温刚好，倒入其中的鸡蛋被热油塑出形状。

鸡蛋总是这样，只要给予温度，便会改变形状。

谁又不是呢？

翻腾的热油正好成为小提琴声的伴奏。

向热牛奶中倒入燕麦，如此，早餐算是完成了。

用比起烹饪更短的时间吃完早餐，我又用比起吃饭更久的时间来清洗锅灶和餐具。

有些时候我真会分不清，餐具存在的意义究竟是被人清洗，还是用来吃饭。

7:22，这是我手表上的时间。

出门前最后一次来到洗手台，看向镜中的自己。

我确认一切都足够妥当，才踏出屋门。

公寓的开放式楼梯上堆了不少邻居家的杂物。

我在杂物间穿行，小心地避开那积满灰尘的障碍。

走过庭院，推动锈蚀的金属院门，暗红的锈色蹭上手掌。

我绕着院墙一直来到公寓侧面的泊车位。

一辆宾利横停在我的车位上，像个臃肿的暴发户一样占了两个车位。

我走过那辆车，公文包捏得有些紧。

想着，算了，他也一定是因为生活不易吧。

走到倾斜的草坪上，我进入自己那辆刚付过首付的大切诺基。

插入钥匙，扭动。

引擎发出一阵疲惫的哀嚎，之后就像个垂死的老人一样熄灭。

再一次，又一次。

像个哮喘患者。

直到我愤怒地将公文包砸在方向盘上，引擎才在一连串咳嗽之后运转起来。

接连经历的五个红色信号灯，还有左拐时不开转向灯的傻逼。

一切都让我窒息，也或许只是车内的空调又出故障了。

来到公司，经过一楼的前台，对谁都会友善问候的女员工同样与我寒暄，随后便更热情地迎向我身后的领导。

我知道，这女人其实不在乎我。

我只是个道具，供舞台上的演员使用。

走进电梯之前，我首先需要恭敬地等候在门口。等那个和女员工搭讪两分钟的领导走过来。

“17楼。”

“是，先生。”

我像个电梯里的侍应生，首先按下17楼，等目送着领导离开之后才按自己需要的12楼。

踏出电梯的第一个瞬间，我就听到了一阵嘈杂。

这是这里的常态，像是一个病态的玻璃清洁工在用硬质的金属毛刷蹂躏玻璃。

“你，站住。看看表。”

我低头看向手表，8:30。恰到好处的准时。

“看墙上的表!”别着主管胸牌的男人扯起我的耳朵，让我抬头。

8:32。

每个人都知道，那块表被主管调快了。

“抱歉，我在电梯里遇到了欧文先生，我们先去了17楼。”

“这不是理由。现在回到你的工位上。”

“是，先生。”

工作，不是什么能让人燃起激情的工作。

如果我能像儿时的愿望那样，成为一名艺术家，或是一名作家，我可能会对工作抱有热情。

但不是这个。

我是个对冲基金公司的数据分析员，我的工作是从各种信息里摘录出数字，把这些数字投放进一套非专业人员一定会一头雾水的系统里，再从系统里得到运算结果。

之后，还要把新的数字投放进另一个系统，并重复这个流程。

讽刺的是，只要给程序中加入一两行指令，这一切都可以自动化完成。

也许那时我需要做的就只是按下0，再按下1。

如果我是我的领导，或是职务里带上高级两个字的什么人。

我还需要定期对这些系统进行评估和分析，幸亏我不是。

电脑屏幕上的时间随着这些数字一起变化，直到主管的尖锐声音从扩音器中响起。

像是金属磨擦一样刺耳，或者说他的嗓子根本就是个金属桶，里面装着各种链条和铁片。

他本可以从不到十米之外的隔音办公室里走出来，对埋头苦干的众人宣布午休。

但或许是那样无法佐证他的权威。

他喜欢扩音器，喜欢那种电子啸叫出的撕裂声音。

或许，主管他也只是因为生活不易吧，我如此想。

拥挤的员工餐厅。

每个人都像是饥饿哭泣的巨婴，走向如肉山一样的妈妈那里，挤压它的乳房，捧着自己那份被人施舍的乳汁离去。

下午，是相同的工作。

所有人都被囚禁在不足四平米的方形牢房里，成为面前机器的奴隶，为它奉上神圣的数字，并得到圣谕一样的反馈。

表格，表格，表格。

数字，数字，数字。

我不像是一个人，像是在表格里跳动的数字。

公司就是一本数据簿，部门就是一张张数据表，我们只是符号，只是字符。

啪。一只有力的大手将我拉回现实。

“下班之前，我要在邮箱里看到这些的电子表。”

一叠厚厚的报表被丢在我桌上。

在几米之外就有一台带扫描功能的复印机。

但那个带着主管牌子的男人却不用。

我知道，他并不是愚蠢到不会用科技产品，只是为了佐证他的权威，惩戒那些胆敢迟到的人。

“是，先生。”

18:47。

领导离开的时间。

早在几个小时之前我就将报表发到了他的邮箱里。

“数据有几个错误，你下班之前重新校对一遍。”

这么说着，主管走了。

20:26。

这是我走出公司大门的时间。

公司的每一层都灯火通明，但其实已经没什么人了。

我知道，这不是因为所有人都是忘记关灯的傻子，只是想装出很忙碌的样子。

因为忙碌的公司才会业务多，业务多的公司才会有前途，有前途的公司却不可能只有一家。

这一切，不过是活在不关灯困境里的飞虫。

向灯罩扣住的光源发起一次次冲锋，直到撞得脑浆涂地。

回家的路上，夜晚20点的城市依旧拥堵。

人类就像是最廉价的畜生，尽情繁衍，尽情狂欢。

我回到公寓旁的泊车场，发现那台宾利还横停在自己的车位上，只不过车头改了个朝向。

大概，他忘了自己的车位在哪吧，我这么想。

我把车停在斜着的草坪上，在拉住手刹之前，车轮先一步被重力牵引。

还来不及踩刹车，大切诺基一路后退着撞上了街边的电线杆。

黑色的漆壳上留下一条长长的擦痕。

“妈的。”

我看向不远处反射着月光的宾利，眼里的愤怒逐渐变成无奈。

再次小心地把车停好，我穿过一排排杂物，来到自家门前。

“缴费通知单，水电费欠缴:624元。”

我才刚搬来半个月。

因为这里是距离我公司最近的几处出租公寓里，最便宜的那个。

“你妈的。”

我一把撕下通知单，摔门进屋。

或是说，先进屋，再摔门。

我来到冰箱前，打开柜门看到的是空无一物的冰箱，只有半袋吐司还藏在角落里。

显然，有我钥匙的女友不久前造访过。

餐桌上的食品包装袋和凌乱的沙发也能证明这点。

我并不渴望恋人，那只是家里人逼着我相亲认识的一个女人。

该考虑换个锁了。

来到浴室，我想用凉水让自己冷静冷静，可水龙头却只对我呕出一滩黄色的浓痰，然后再无动静。

我想起了缴费通知单。

碰!我用力砸在水龙头的金属握把上。

一种难以言喻的愤怒冲上我的脑颅。

碰。

第二下。

碰。

第三下。

碰...碰，碰碰碰碰。

一直到我被痛觉唤醒，发现手掌鲜红。

金属握把断成了两半，尖锐的棱角刺进我的肉里。

啪啦。

我一把将放在洗手台边的牙杯打翻。

翻开镜子后的储物格，拿出里面储备的急救物品来。

其实只是酒精、棉球和纱布。

我给伤口消毒包扎，忍受着疼痛和愤怒。

我来到床前，随便几下把衣服扯掉，整个人倒了下去。

半夜，我被一阵啼哭声惊醒。

看向荧光的电子表，2:11。

是楼下家小孩的哭声。

随后是一片声音。

小孩的外婆唱起愚蠢的童谣，父亲在破口大骂，母亲和父亲对骂，到后来外婆也跟着骂起来。

之后，是更多被吵醒的邻居的骂声。

像是给一池积满排泄物的坑里丢下一枚炸弹。

让人发狂的噪音又持续了半个小时才消停。

我紧紧闭着眼，却没能入睡。

再次看向电子表。

3:54。

下一次是，5:22。

再下一次已经不用看了，因为天已经亮了。

我恼怒地用枕头埋住自己的头，像个慌乱的鸵鸟。

“你妈的。”

我这么骂了一句，捡起地上散乱的衣服，将之穿好，随后出门。

之后是，同样的一天。





# part 2

这世界不是一幕发人深思的悲剧，没有作家在这里修饰出深沉的希望和炽热的幻想。

它注定将成为一出乏味无趣的叙事剧，做出成百上千次相同的演出，把戏服穿得褪色、破烂。

而我们，就像是臃肿的教典上，不断吸吮着脓疮的修士。

贪婪也好、虔诚也罢。

无论多少次，能得到的也只是一滩令人作呕的汁水。

闹钟声把我吵醒。

6:40，这是现在的时间。

我端坐在电脑桌前，机械性地将一个又一个数据录入系统，并得到另一串数据。

一只有力的大手拍在我背上。

我知道，他不是愚蠢，只是为了佐证权威。

宾利横在我的车位上。

拥挤阻塞的开放式楼梯，蹭了一身污水和灰尘。

我用力拨开被砸坏的水龙头把手，却发现没有一滴水流出来。

我想起了缴费通知单。

我来到员工食堂，每个人都像是巨婴一样，渴望着臃肿如肉山一样的母亲，哺育其以母乳。

我对公司前台的年轻女士微笑。

我为领导按下17层按钮。

我将一个又一个数据录入系统。

我对比一条条曲线。

我抬起拳头想要砸在宾利反光的外壳上，最终只能轻轻放下。

我暴躁地翻开冰箱门。

我修理起卡纸的复印机。

我将碍事的盆栽向后挪动2厘米。

我打开收音机，里面传来沙沙的噪音。

我用力跺着地板，试图让楼下安静点。

我开始嘲笑三角形。

我认为蜡烛的红色是不必要的。

我发觉键盘在低声和我说话。

我认为帽子应该会飞。

我彻夜难眠。

我找到一条通向贝壳里的路。

我觉得员工食堂的饭菜令人作呕。

我试图让杯子明白，气球是不会爱上它的。

我拨起电话破口大骂。

我觉得门在向我招手。

我猜测一天或许有60个小时。

我在陌生的地方醒来。

我因在工作期间睡着被骂。

我只喜欢会跳踢踏舞的三明治。

我推测罐头在下班期间不会吃凤梨。

我厉声呵斥纸卷的愚蠢行径。

我感到困倦，但我无法睡下。

我发现醒来时传单不见了。

我在同一天里经历了两次6:40。

我对游泳池深情告白。

我喜欢水，但水不喜欢我。

我来到心理医师面前，并厉声强调我只是因为失眠而有些焦虑和疲惫。

我被诊断为患有双向障碍，但我坚信那个庸医只是想骗我的钱。

我再次停车到倾斜的草坡上。

我的衣服被旧洗衣机的棱角刮破。

我已经几天没有洗澡了。

我突然觉得，自己似乎在梦里。





# Part 3

啪嗒。一只手按在闹钟上，扼紧它的喉咙。

6:40，这是他睁开眼看到的时间。

再度与每天的第一缕阳光幽会，又或是说，吻别这终将离去的太阳。

起床。重新唤醒这僵直的身体。

干瘪的肉体摩擦着骨骼，发出一阵阵骇人的声响。

每次睡眠都无异于一次短暂的死亡，直到再也无法苏醒为止。

相反的，死亡亦是长眠，而他只是经常在梦中惊醒。

洗漱。干瘪的牙刷毛刺嵌入肉里，牙龈的皮肉被刮下。

或许，他该看看牙科医生了，不管他怎么刷牙，牙齿的状况都在恶化。

穿衣。破旧的衬衣、肮脏的外套和长裤。补丁已经打满了，上面却还都是破洞。

这些勾勒出他一米九的身材。可暗褐色的污迹覆盖住镜子，扭曲的镜中只反射出一个不成人形的佝偻身影。

也许，该找个时间好好休息一阵。

他来到起居室内的开放式厨房，打开放在置物隔断第一排的收音机。

沙沙沙的噪音代替了应有的美妙旋律，不知多久之前，电台的信号就已消失不见。

他打开烤面包机，想将吐司片放入其中。

吐司机被按下，却因里面空无一物弹了起来。

加热元件早已损坏，只剩下两根弹簧孤零零地运作。

煎锅里的油渍挤满一层，丢入其中的蛋壳孤独地滚动。与收音机的噪音公成一曲。

一只快要饿死的蟑螂从橱柜里掉了下来，奄奄一息。

拿起褶皱的牛奶盒，无论如何倾倒也到不出一滴。

污痕在碗上形成模糊的手印，碗中空无一物，他却将空气一饮而尽。

用比起烹饪更短的时间吃完早餐，他又用比起吃饭更久的时间来清洗锅灶和餐具。

清洁布和毛刷在干燥的厨具上摩擦，发出一阵刺耳的声响。

他却在思考：餐具存在的意义究竟是被人清洗，还是用来吃饭。

7:22，这不是他手表上的时间。

他看向光溜溜的手腕，皮肤早已溃烂，那里白骨外露。

出门前最后一次来到洗手台，看向镜中的自己。

他确认一切都足够妥当，才踏出屋门。

公寓的开放式楼梯上堆了不少邻居家的杂物。

他在杂物间穿行，小心地避开那积满灰尘的障碍。

苍蝇在恶臭的烂肉上窜动，干涸的血浆和撕烂的衣物黏成一团，一切都东倒西歪，无从落脚。

走过庭院，推动锈蚀的金属院门，暗红的血浆蹭上手掌。

他绕着院墙一直来到公寓侧面的泊车位。

这里只有两辆车。

一辆宾利横停在他的车位上，像个臃肿的暴发户一样占了相邻的两个车位。

另一辆玻璃破烂的大切诺基突兀地停在一旁光秃秃的草坪上。

车漆上遍布着凌乱的抓痕，只剩左侧的车门孤零零悬挂着。

他走过那辆车，公文包捏得有些紧。而那公文包的下半部分早已被撕烂。

想着，算了，他也一定是因为生活不易吧。

走到倾斜的草坡上，他进入自己那辆早已报废的大切诺基。

插入钥匙，扭动。引擎发不出任何动静。燃油表的指针早已停在E的位置。

这辆车就像一具铁棺材，却比棺材更加透风。

他愤怒地将公文包砸在方向盘上，激起一团飞尘。

他走下车，一路走过破败的街道。

接连经历的五个停电失效的信号灯，还有突然奔向左侧的干瘪行尸。

一切都令他感到窒息，也或许只是他的气管早已朽烂。

这破旧的城市废墟中早已没了水源，高悬于空的烈日炙烤着遍体鳞伤的大地。

来到公司，经过一楼的前台，对谁都会友善问候的女员工与他寒暄。

坐在工位上的充气假人早就漏光了气，只剩下一层被撕烂的皮套丢在缺了一条腿的椅子上。

那东西永远保持着一副丑陋的笑容，无论走来的是谁。

走进电梯之前，他首先需要恭敬地等候在门口，等那个和女员工搭讪两分钟的领导走过来。

尽管一切都只是臆想，他还是说了：“是，先生。”

他像个电梯里的侍应生，首先按下了17楼，过了很久才按下自己需要的12楼。

电梯毫无动静，毕竟它一直停在这里。

踏出电梯的第一个瞬间，他就听到了一阵嘈杂。

这是这里的常态，一群行走的烂肉在远处摩擦着摇摇欲坠的金属隔离网。

那声音像是一个病态的玻璃清洁工在用硬质的金属毛刷蹂躏玻璃。

他低头看向空无一物的手腕

很快就面露痛苦地仰起头，看向墙上挂着的表。

8:32。

覆满尘土的表盘里，指针始终停在那。

这一片狼藉的办公室里，除他以外就再无一人。

......





# Part 4

6:40，这是我睁开眼看到的时间。

再度与每天的第一缕阳光幽会，又或是说，吻别这终将离去的太阳。

起床。重新唤醒这僵直的身体。

每次睡眠都无异于一次短暂的死亡，直到再也无法苏醒为止。

倘若这世界是一场戏剧，它一定是无悲无喜的。

没有发人深思的悲伤，也没有深沉炽烈的幻想。

它只是一出乏味无趣的叙事剧，做出成百上千次相同的演出。

只等着演员变得年老体衰，戏服变得褪色残破。

随后，将之吞噬殆尽。

而我们，不过是依偎在臃肿的教典上，不断吸吮着脓疮的修士。

贪婪也好、虔诚也罢。

无论多少次，能得到的也只是一滩令人作呕的汁水。